language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer require browserfs/string

script: phpunit

# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
    fast_finish: true

notifications:
    on_success: never
    on_failure: always
